### ISSUE TITLE
Region cli argument

### ISSUE THREAD

**Issue by notatestuser** [samsoul007/ecs-aws#1]
It would be great to be able to do something like:
```
ecs-aws [command] --profile prof --region ap-southeast-1
```
with a fallback to `eu-west-1` by default.

**Comment by samsoul007** [comment]
hi @notatestuser 
I am about to have a new version and I will include your request.

It will be set when you configure a profile as clusters, services, etc are region specific.
Sorry for the late reply, didn't got the notification...

cheers.

**Comment by samsoul007** [comment]
I have deployed a new minor version handling the region in the configuration. 
There is also an alpha feature for cronjob/schedule tasks deployement, where it is possible to deploy a schedule task but it won't update the task definition number when deployed (aws handles those tasks in a very weird way inside cloudwatch).
